[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
marlin = "MRLNxMrRgKMFnHEuJPsWnbDzDRKdNHvisijd7Gg6MjZ"

[programs.devnet]
marlin = "MRLNxMrRgKMFnHEuJPsWnbDzDRKdNHvisijd7Gg6MjZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
